import os
import random
import re
import sys
import math

DAMPING = 0.85
SAMPLES = 10000


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python pagerank.py corpus")
    corpus = crawl(sys.argv[1])
    ranks = sample_pagerank(corpus, DAMPING, SAMPLES)
    print(f"PageRank Results from Sampling (n = {SAMPLES})")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")
    ranks = iterate_pagerank(corpus, DAMPING)
    print(f"PageRank Results from Iteration")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")


def crawl(directory):
    """
    Parse a directory of HTML pages and check for links to other pages.
    Return a dictionary where each key is a page, and values are
    a list of all other pages in the corpus that are linked to by the page.
    """
    pages = dict()

    # Extract all links from HTML files
    for filename in os.listdir(directory):
        if not filename.endswith(".html"):
            continue
        with open(os.path.join(directory, filename)) as f:
            contents = f.read()
            links = re.findall(r"<a\s+(?:[^>]*?)href=\"([^\"]*)\"", contents)
            pages[filename] = set(links) - {filename}

    # Only include links to other pages in the corpus
    for filename in pages:
        pages[filename] = set(
            link for link in pages[filename]
            if link in pages
        )

    return pages


def transition_model(corpus, page, damping_factor):
    """
    Return a probability distribution over which page to visit next,
    given a current page.

    With probability `damping_factor`, choose a link at random
    linked to by `page`. With probability `1 - damping_factor`, choose
    a link at random chosen from all pages in the corpus.
    """

    probability_distribution = {}

    # Case page has no links
    if len(corpus[page]) == 0:
        probability = 1 / len(corpus.keys())
        for p in corpus.keys():
            probability_distribution.update({p:probability})
    # I iterate over all keys and add the default probability ( (1-damping) / nr_of_pages ) and for linked pages of page add damping/nr_of_linked_pages
    else:
        default_probability = (1 - damping_factor) / len(corpus.keys())
        for p in corpus.keys():
            prob = default_probability
            probability_distribution.update({p:prob})
        linked_probability = damping_factor / len(corpus[page])
        for p in corpus[page]:
            probability_distribution[p] += linked_probability

    return probability_distribution


    
    


def sample_pagerank(corpus, damping_factor, n):
    """
    Return PageRank values for each page by sampling `n` pages
    according to transition model, starting with a page at random.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    pagerank = dict()
    sample = None
    random.seed()

    for page in corpus:
        pagerank[page] = 0

    for step in range(n):
        if sample is None:
            # First sample generated by choosing from a page at random
            sample = random.choices(list(corpus.keys()), k=1)[0]
        else:
            # Next sample generated from the previous one based on its transition model
            model = transition_model(corpus, sample, damping_factor)
            population, weights = zip(*model.items())
            sample = random.choices(population, weights=weights, k=1)[0]

        pagerank[sample] += 1

    # Normalize the results
    for page in corpus:
        pagerank[page] /= n

    return pagerank


def iterate_pagerank(corpus, damping_factor):
    """
    Return PageRank values for each page by iteratively updating
    PageRank values until convergence.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # Initialize empty dictionary
    pagerank = dict()
    newrank  = dict()

    for p in corpus.keys():
        pagerank[p] = 1/len(corpus.keys())

    repeat = True

    while repeat:

        for page in pagerank:
            link_prob = float(0)
            for possible_page in corpus:

                # If page is in corpus probability is PR of page divided by the number of link on that page
                if page in corpus[possible_page]:
                    link_prob +=  pagerank[possible_page] / len(corpus[possible_page])
                
                if not corpus[possible_page]:
                    link_prob += pagerank[possible_page] / len(corpus)
                
                newrank[page] = (1-damping_factor)/len(corpus) + damping_factor * link_prob
        
        repeat = False

        for page in pagerank:
            # Check for each page if it changes more then threashold
            if not math.isclose(newrank[page], pagerank[page], abs_tol=0.001):
                repeat = True
            # Assign new values to current values
            pagerank[page] = newrank[page]
    
    return pagerank




if __name__ == "__main__":
    main()
